1. Data Normalization, std, scaling, preprocesing
2. Web Scrapping
3. Re Library - clean text data
4. Visualisation

In [ ]:
# import the library
import pandas as pd
import numpy as np
print('All lib imported')

All lib imported


In [ ]:
url1 = 'https://raw.githubusercontent.com/shawnkan/Simpli/main/New_data.csv'
# read the data
data=pd.read_csv(url1)

In [ ]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
data.shape

(10, 4)

In [ ]:
data.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

# Data Preprocessing

pandas only

scikit learn

In [ ]:
# Data Preprocessing using pandas
data['Age'].fillna(data['Age'].mean(),inplace=True)
data['Salary'].fillna(data['Salary'].mean(),inplace=True)

In [ ]:
data.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [ ]:
data

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [ ]:
# convert all categorical features into numeric one
data['Purchased']=data['Purchased'].replace({'Yes':1,'No':0})

In [ ]:
data

Country        Age        Salary  Purchased
0   France  44.000000  72000.000000          0
1    Spain  27.000000  48000.000000          1
2  Germany  30.000000  54000.000000          0
3    Spain  38.000000  61000.000000          0
4  Germany  40.000000  63777.777778          1
5   France  35.000000  58000.000000          1
6    Spain  38.777778  52000.000000          0
7   France  48.000000  79000.000000          1
8  Germany  50.000000  83000.000000          0
9   France  37.000000  67000.000000          1

In [ ]:
data['Country'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

one hot encoding / dummy encoding\
green \
yellow\
red


green  yellow  red\
1      0       0\
0      1       0\
0      0       1

In [ ]:
data=pd.get_dummies(data)

In [ ]:
data

Age        Salary  Purchased  Country_France  Country_Germany  \
0  44.000000  72000.000000          0               1                0   
1  27.000000  48000.000000          1               0                0   
2  30.000000  54000.000000          0               0                1   
3  38.000000  61000.000000          0               0                0   
4  40.000000  63777.777778          1               0                1   
5  35.000000  58000.000000          1               1                0   
6  38.777778  52000.000000          0               0                0   
7  48.000000  79000.000000          1               1                0   
8  50.000000  83000.000000          0               0                1   
9  37.000000  67000.000000          1               1                0   

   Country_Spain  
0              0  
1              1  
2              0  
3              1  
4              0  
5              0  
6              1  
7              0  
8              0  
9              0

# Scale the data

0 to 1

z-score / standard scaler
measure of how many std a particular data point is from mean of group of data

z= value-mean / std

In [ ]:
df_z_scaled=data.copy()

In [ ]:
#apply normalization technique (Z Score normalization)

for column in df_z_scaled:
  if df_z_scaled[column].dtypes == float:
    df_z_scaled[column]=(df_z_scaled[column]-df_z_scaled[column].mean())/df_z_scaled[column].std()

In [ ]:
df_z_scaled

Age        Salary  Purchased  Country_France  Country_Germany  \
0  0.719931  7.110128e-01          0               1                0   
1 -1.623675 -1.364376e+00          1               0                0   
2 -1.210098 -8.455287e-01          0               0                1   
3 -0.107224 -2.402070e-01          0               0                0   
4  0.168495  6.291850e-16          1               0                1   
5 -0.520801 -4.996306e-01          1               1                0   
6  0.000000 -1.018478e+00          0               0                0   
7  1.271368  1.316334e+00          1               1                0   
8  1.547087  1.662233e+00          0               0                1   
9 -0.245083  2.786401e-01          1               1                0   

   Country_Spain  
0              0  
1              1  
2              0  
3              1  
4              0  
5              0  
6              1  
7              0  
8              0  
9              0

In [ ]:
# min max scaling
# it scales the values of a feature to specific range between 0 and 1
# Xscaled = (X-Xmin)/(Xmax-Xmin)
df_min_max_scaled=data.copy()

In [ ]:
for column in df_min_max_scaled.columns:
    if df_min_max_scaled[column].dtypes==float:
      df_min_max_scaled[column]=(df_min_max_scaled[column]-df_min_max_scaled[column].min())/(df_min_max_scaled[column].max()-df_min_max_scaled[column].min())

In [ ]:
df_min_max_scaled

Age    Salary  Purchased  Country_France  Country_Germany  \
0  0.739130  0.685714          0               1                0   
1  0.000000  0.000000          1               0                0   
2  0.130435  0.171429          0               0                1   
3  0.478261  0.371429          0               0                0   
4  0.565217  0.450794          1               0                1   
5  0.347826  0.285714          1               1                0   
6  0.512077  0.114286          0               0                0   
7  0.913043  0.885714          1               1                0   
8  1.000000  1.000000          0               0                1   
9  0.434783  0.542857          1               1                0   

   Country_Spain  
0              0  
1              1  
2              0  
3              1  
4              0  
5              0  
6              1  
7              0  
8              0  
9              0

In [68]:
# read the data
data=pd.read_csv(url1)

In [69]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [70]:
#extract independent and dependent variables from the data in array
# if don't use values, then output is dataframe format.
# for ML should be array

X = data.iloc[:,:-1].values
y= data.iloc[:,-1].values

In [71]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [72]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [73]:
# handle missing data
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [74]:
imputer.fit(X[:,1:3]) #learning, training
X[:,1:3]=imputer.transform(X[:,1:3]) #transform: telling you do it

In [75]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

ML projects need pipelines

all need to be preprocessed the same way

pipelines are more convenient

In [76]:
# convert categorical into numerical

In [77]:
# convert 0 1 2 3 4 5
# cheat code, normally camel case is class
from sklearn.preprocessing import LabelEncoder
label_en=LabelEncoder()

In [78]:
y=label_en.fit_transform(y)


In [79]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [80]:
label_en.classes_

array(['No', 'Yes'], dtype=object)

In [81]:
label_en.inverse_transform([1,0])

array(['Yes', 'No'], dtype=object)

In [82]:
# sklearn one hot encoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#'encoder' can be anyting
#[0] is apply on first column
# pass through is columns not affected passthrough
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [83]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [84]:
# z score /scaling on data

# create split of data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

In [85]:
X_train.shape

(8, 5)

In [86]:
X_train

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [87]:
y_train

array([0, 0, 1, 0, 0, 1, 0, 1])

In [88]:
# standard scaler
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [89]:
# only scale on selective column
# fit transform because learning and transforming happening together
col=[3,4]
X_train[:,col]=sc.fit_transform(X_train[:,col])

In [90]:
X_train

array([[0.0, 1.0, 0.0, -1.597964298767881, -1.093614878729163],
       [1.0, 0.0, 0.0, 0.6176450728387547, 0.5817100418772143],
       [1.0, 0.0, 0.0, -0.4901596129645631, 0.11634200837544287],
       [0.0, 0.0, 1.0, -0.20881239117324418, -1.2797620921298716],
       [0.0, 1.0, 0.0, 1.5671919463844557, 1.6055197155811116],
       [1.0, 0.0, 0.0, 1.250676321869222, 1.2332252887796944],
       [0.0, 0.0, 1.0, -0.3319018007069463, -0.4420996318266829],
       [1.0, 0.0, 0.0, -0.8066752374797969, -0.7213204519277457]],
      dtype=object)

In [91]:
#use transform and not fit transform as object already trained earlier
#data leakage, make the model biased on data
# we should not train it on test data
X_test[:,col]=sc.transform(X_test[:,col])

In [92]:
X_test

array([[0.0, 1.0, 0.0, -0.015386176191712623, -0.18356183543680957],
       [0.0, 0.0, 1.0, -2.0727377355407315, -1.6520565189312888]],
      dtype=object)

In [93]:
# z score /scaling on data

# create split of data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

In [94]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [95]:
col=[3,4]
X_train[:,col]=scaler.fit_transform(X_train[:,col])

In [96]:
col=[3,4]
X_test[:,col]=scaler.transform(X_test[:,col])

In [97]:
X_train

array([[0.0, 1.0, 0.0, 0.5652173913043479, 0.45079365079365075],
       [1.0, 0.0, 0.0, 0.43478260869565233, 0.5428571428571427],
       [1.0, 0.0, 0.0, 0.34782608695652173, 0.2857142857142856],
       [0.0, 0.0, 1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0, 1.0, 1.0],
       [1.0, 0.0, 0.0, 0.7391304347826089, 0.6857142857142855],
       [0.0, 0.0, 1.0, 0.4782608695652175, 0.37142857142857144],
       [0.0, 0.0, 1.0, 0.5120772946859904, 0.11428571428571432]],
      dtype=object)

In [98]:
X_test

array([[1.0, 0.0, 0.0, 0.9130434782608696, 0.8857142857142857],
       [0.0, 1.0, 0.0, 0.1304347826086958, 0.17142857142857149]],
      dtype=object)

all lib imported


MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0          SC60       RL         65.0     8450   Pave  None      Reg   
1          SC20       RL         80.0     9600   Pave  None      Reg   
2          SC60       RL         68.0    11250   Pave  None      IR1   
3          SC70       RL         60.0     9550   Pave  None      IR1   
4          SC60       RL         84.0    14260   Pave  None      IR1   
...         ...      ...          ...      ...    ...   ...      ...   
1455       SC60       RL         62.0     7917   Pave  None      Reg   
1456       SC20       RL         85.0    13175   Pave  None      Reg   
1457       SC70       RL         66.0     9042   Pave  None      Reg   
1458       SC20       RL         68.0     9717   Pave  None      Reg   
1459       SC20       RL         75.0     9937   Pave  None      Reg   

     LandContour Utilities LotConfig  ... PoolArea PoolQC  Fence MiscFeature  \
0            Lvl    AllPub    Inside  ...        0     No     No          No   
1            Lvl    AllPub       FR2  ...        0     No     No          No   
2            Lvl    AllPub    Inside  ...        0     No     No          No   
3            Lvl    AllPub    Corner  ...        0     No     No          No   
4            Lvl    AllPub       FR2  ...        0     No     No          No   
...          ...       ...       ...  ...      ...    ...    ...         ...   
1455         Lvl    AllPub    Inside  ...        0     No     No          No   
1456         Lvl    AllPub    Inside  ...        0     No  MnPrv          No   
1457         Lvl    AllPub    Inside  ...        0     No  GdPrv        Shed   
1458         Lvl    AllPub    Inside  ...        0     No     No          No   
1459         Lvl    AllPub    Inside  ...        0     No     No          No   

     MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0          0    Feb    2008        WD         Normal     208500  
1          0    May    2007        WD         Normal     181500  
2          0    Sep    2008        WD         Normal     223500  
3          0    Feb    2006        WD        Abnorml     140000  
4          0    Dec    2008        WD         Normal     250000  
...      ...    ...     ...       ...            ...        ...  
1455       0    Aug    2007        WD         Normal     175000  
1456       0    Feb    2010        WD         Normal     210000  
1457    2500    May    2010        WD         Normal     266500  
1458       0    Apr    2010        WD         Normal     142125  
1459       0    Jun    2008        WD         Normal     147500  

[1460 rows x 80 columns]